resolver: lts-13.25

packages:
- .

extra-deps:
  - github: idontgetoutmuch/Naperian
    commit: 54d873ffe99de865ca34e6bb3b92736e29e01619
    size: 7146
    sha256: b656cac6fbed9982514675ff1780c50e261a53673d25c4d3ed7b6957f334b6ea
  - ../hasktorch/codegen
  - ../hasktorch/libtorch-ffi
  - ../hasktorch/hasktorch
  - ../hasktorch/inline-c/inline-c-cpp
  - ../hasktorch/inline-c/inline-c

extra-include-dirs:
  - ../hasktorch/deps/libtorch/include
  - ../hasktorch/deps/libtorch/include/torch/csrc/api/include

extra-lib-dirs: 
  - ../hasktorch/deps/libtorch/lib/
  - ../hasktorch/deps/mklml/lib/