resolver: lts-13.25

packages:
- .

extra-deps:
  - github: idontgetoutmuch/Naperian
    commit: 54d873ffe99de865ca34e6bb3b92736e29e01619
    size: 7146
    sha256: b656cac6fbed9982514675ff1780c50e261a53673d25c4d3ed7b6957f334b6ea
  - extensible-0.5.1@sha256:27cb6a6c9101c2d146fa227d09ae683d02bcd723f30a4f4e7e82d6b1c5733c23,2846
  - membership-0@sha256:3a11d8fd53cb1a76bb9273e6c929bbf9d649f109714bf487abb3143be04ddc81,995
  - constraints-0.11
  - ../ffi-experimental/codegen
  - ../ffi-experimental/ffi
  - ../ffi-experimental/hasktorch
  - ../ffi-experimental/inline-c/inline-c-cpp
  - ../ffi-experimental/inline-c/inline-c

extra-include-dirs:
  - ../ffi-experimental/deps/libtorch/include
  - ../ffi-experimental/deps/libtorch/include/torch/csrc/api/include

extra-lib-dirs: 
  - ../ffi-experimental/deps/libtorch/lib/
  - ../ffi-experimental/deps/mklml/lib/